import React, { useState } from 'react';
import { 
  Rocket, 
  ExternalLink, 
  Copy, 
  Check, 
  Database, 
  Code, 
  Target, 
  Download,
  Terminal,
  FileCode
} from 'lucide-react';
import { SOCIAL_IMPACT_PROJECTS } from '../data/socialImpactTemplates';
import { renderBionicText } from '../utils/textUtils';

export default function EmpowermentLaunchpad({ bionicReading }) {
  const [selectedProjectId, setSelectedProjectId] = useState('neuro-read');
  const [copiedCode, setCopiedCode] = useState(false);
  const [activeTab, setActiveTab] = useState('overview'); // 'overview' | 'architecture' | 'code' | 'datasets'

  const project = SOCIAL_IMPACT_PROJECTS.find(p => p.id === selectedProjectId) || SOCIAL_IMPACT_PROJECTS[0];

  const handleCopyCode = () => {
    navigator.clipboard.writeText(project.starterCodePython);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);
  };

  const handleExportBlueprint = () => {
    const markdown = `# ${project.title}
**SDG Alignment:** ${project.sdg}
**Target Beneficiaries:** ${project.targetUsers}

## 1. Problem Statement
${project.problem}

## 2. Solution Overview
${project.solution}

## 3. Machine Learning Technique & Architecture
${project.aiTechnique}

\`\`\`
${project.architecture}
\`\`\`

## 4. Starter Code
\`\`\`python
${project.starterCodePython}
\`\`\`

## 5. Recommended Datasets
${project.recommendedDatasets.map(d => `- [${d.name}](${d.url}): ${d.desc}`).join('\n')}

---
*Generated by Minerva Empowerment Launchpad for ML Empowerment Build Challenge*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.id}-blueprint.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      
      {/* Header & Blueprint Selector */}
      <div className="ui-panel p-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-3 pb-3 border-b border-white/[0.06]">
          <div>
            <span className="text-[11px] font-mono text-emerald-400 uppercase tracking-wider block">
              Dall'Apprendimento all'Azione Sociale
            </span>
            <h1 className="text-xl font-bold tracking-tight text-zinc-100 font-['Outfit']">
              Blueprint di Progetto (UN SDG Framework)
            </h1>
          </div>

          <button
            onClick={handleExportBlueprint}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-100 hover:bg-white text-zinc-950 font-semibold text-xs transition-colors cursor-pointer self-start sm:self-auto"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Esporta Spec (.md)</span>
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
          {SOCIAL_IMPACT_PROJECTS.map((p) => {
            const isSelected = p.id === selectedProjectId;
            return (
              <button
                key={p.id}
                onClick={() => setSelectedProjectId(p.id)}
                className={`p-3 rounded-lg border text-left transition-all cursor-pointer ${
                  isSelected
                    ? 'bg-zinc-800 text-white border-white/10 shadow-sm'
                    : 'bg-zinc-900/40 border-white/[0.06] text-zinc-400 hover:text-zinc-200'
                }`}
              >
                <div className="text-[10px] font-mono text-emerald-400 mb-1">
                  {p.sdg.split(':')[0]}
                </div>
                <div className="text-xs font-semibold text-zinc-200 truncate">
                  {p.title.split(':')[0]}
                </div>
                <div className="text-[11px] text-zinc-500 truncate mt-0.5">
                  {p.targetUsers.split(',')[0]}
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Spec Sheet */}
      <div className="ui-panel p-6 space-y-5">
        
        {/* Project Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-white/[0.06]">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-[11px] font-mono text-emerald-400 px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20">
                {project.sdg}
              </span>
              <span className="text-[11px] text-zinc-400 font-mono">
                Destinatari: {project.targetUsers}
              </span>
            </div>
            <h2 className="text-xl font-bold tracking-tight text-zinc-100 font-['Outfit']">
              {project.title}
            </h2>
          </div>

          <div className="flex items-center p-1 rounded-lg bg-zinc-900/80 border border-white/[0.08] self-start sm:self-auto text-xs">
            <button
              onClick={() => setActiveTab('overview')}
              className={`px-3 py-1.5 rounded-md font-medium transition-all cursor-pointer ${
                activeTab === 'overview' ? 'bg-zinc-800 text-white font-semibold' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              Panoramica
            </button>
            <button
              onClick={() => setActiveTab('architecture')}
              className={`px-3 py-1.5 rounded-md font-medium transition-all cursor-pointer ${
                activeTab === 'architecture' ? 'bg-zinc-800 text-white font-semibold' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              Architettura
            </button>
            <button
              onClick={() => setActiveTab('code')}
              className={`px-3 py-1.5 rounded-md font-medium transition-all cursor-pointer ${
                activeTab === 'code' ? 'bg-zinc-800 text-white font-semibold' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              Codice
            </button>
            <button
              onClick={() => setActiveTab('datasets')}
              className={`px-3 py-1.5 rounded-md font-medium transition-all cursor-pointer ${
                activeTab === 'datasets' ? 'bg-zinc-800 text-white font-semibold' : 'text-zinc-400 hover:text-zinc-200'
              }`}
            >
              Dataset
            </button>
          </div>
        </div>

        {/* Tab 1: Overview */}
        {activeTab === 'overview' && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="ui-panel-elevated p-5 space-y-2">
              <span className="text-[11px] font-mono uppercase tracking-wider text-zinc-400 block">
                Problema nel Mondo Reale
              </span>
              <p className="text-xs sm:text-sm text-zinc-300 leading-relaxed">
                {renderBionicText(project.problem, bionicReading)}
              </p>
            </div>

            <div className="ui-panel-elevated p-5 space-y-2">
              <span className="text-[11px] font-mono uppercase tracking-wider text-emerald-400 block">
                Soluzione Basata su ML
              </span>
              <p className="text-xs sm:text-sm text-zinc-300 leading-relaxed">
                {renderBionicText(project.solution, bionicReading)}
              </p>
            </div>

            <div className="md:col-span-2 p-4 rounded-xl bg-zinc-900/60 border border-white/[0.08] text-xs text-zinc-300 leading-relaxed">
              <span className="font-semibold text-zinc-200 mr-1.5">Value Proposition per i Giudici:</span>
              <span className="italic text-zinc-400">"{project.pitchHook}"</span>
            </div>
          </div>
        )}

        {/* Tab 2: Architecture */}
        {activeTab === 'architecture' && (
          <div className="space-y-3">
            <div className="text-xs text-zinc-400 flex items-center justify-between">
              <span>Pipeline Dati & Modello ({project.aiTechnique}):</span>
              <span className="font-mono text-[11px] text-zinc-500">ASCII Architecture Graph</span>
            </div>
            <pre className="code-block p-4 text-emerald-400 font-mono text-xs overflow-x-auto whitespace-pre leading-relaxed">
              {project.architecture}
            </pre>
          </div>
        )}

        {/* Tab 3: Starter Code */}
        {activeTab === 'code' && (
          <div className="space-y-2.5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono text-zinc-500">pipeline.py</span>
              <button
                onClick={handleCopyCode}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-900 hover:bg-zinc-800 text-zinc-300 text-xs font-medium border border-white/[0.06] transition-colors cursor-pointer"
              >
                {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedCode ? 'Copiato' : 'Copia'}</span>
              </button>
            </div>
            <pre className="code-block p-4 text-zinc-300 font-mono text-xs overflow-x-auto whitespace-pre-wrap leading-relaxed">
              {project.starterCodePython}
            </pre>
          </div>
        )}

        {/* Tab 4: Datasets */}
        {activeTab === 'datasets' && (
          <div className="grid gap-3 sm:grid-cols-2">
            {project.recommendedDatasets.map((ds, idx) => (
              <div key={idx} className="ui-panel-elevated p-4 flex flex-col justify-between space-y-3">
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-semibold text-zinc-200">{ds.name}</span>
                    <Database className="w-3.5 h-3.5 text-zinc-500" />
                  </div>
                  <p className="text-xs text-zinc-400 leading-relaxed">
                    {ds.desc}
                  </p>
                </div>
                <a
                  href={ds.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-400 hover:text-indigo-300 transition-colors"
                >
                  <span>Consulta Dataset Ufficiale</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>
            ))}
          </div>
        )}

      </div>
    </div>
  );
}
