import React, { useState } from 'react';
import { 
  Rocket, 
  ExternalLink, 
  Copy, 
  Check, 
  Globe2, 
  Database, 
  Code, 
  Target, 
  Sparkles, 
  ArrowRight,
  Download,
  BookOpen
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { SOCIAL_IMPACT_PROJECTS } from '../data/socialImpactTemplates';
import { renderBionicText } from '../utils/textUtils';

export default function EmpowermentLaunchpad({ bionicReading }) {
  const [selectedProjectId, setSelectedProjectId] = useState('neuro-read');
  const [copiedCode, setCopiedCode] = useState(false);
  const [activeTab, setActiveTab] = useState('overview'); // 'overview' | 'architecture' | 'code' | 'datasets'

  const project = SOCIAL_IMPACT_PROJECTS.find(p => p.id === selectedProjectId) || SOCIAL_IMPACT_PROJECTS[0];

  const handleCopyCode = () => {
    navigator.clipboard.writeText(project.starterCodePython);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2000);

    confetti({
      particleCount: 25,
      spread: 45,
      origin: { y: 0.8 }
    });
  };

  const handleExportBlueprint = () => {
    const markdown = `# ${project.title}
**SDG Alignment:** ${project.sdg}
**Target Beneficiaries:** ${project.targetUsers}

## 1. Problem Statement
${project.problem}

## 2. Solution Overview
${project.solution}

## 3. Machine Learning Technique & Architecture
${project.aiTechnique}

\`\`\`
${project.architecture}
\`\`\`

## 4. Starter Code
\`\`\`python
${project.starterCodePython}
\`\`\`

## 5. Recommended Datasets
${project.recommendedDatasets.map(d => `- [${d.name}](${d.url}): ${d.desc}`).join('\n')}

---
*Generated by Minerva Empowerment Launchpad for ML Empowerment Build Challenge*
`;

    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${project.id}-blueprint.md`;
    a.click();
    URL.revokeObjectURL(url);

    confetti({
      particleCount: 45,
      spread: 60,
      origin: { y: 0.7 }
    });
  };

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="glass-panel rounded-2xl p-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
          <div>
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 mb-2">
              <Rocket className="w-3.5 h-3.5" />
              <span>Dalla Teoria all'Azione Sociale</span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              Empowerment Launchpad: AI For Good
            </h1>
            <p className="text-sm text-slate-300 mt-1 max-w-3xl">
              Trasforma le competenze apprese in un progetto tangibile ad alto impatto. Seleziona una sfida globale delle Nazioni Unite (SDG) e scopri architettura, codice di partenza e dataset curati.
            </p>
          </div>

          <button
            onClick={handleExportBlueprint}
            className="self-start md:self-center flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-xs shadow-lg shadow-emerald-600/30 transition-all cursor-pointer"
          >
            <Download className="w-4 h-4" />
            <span>Esporta Blueprint (Markdown)</span>
          </button>
        </div>

        {/* Project Selector Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3 pt-2 border-t border-slate-700/50">
          {SOCIAL_IMPACT_PROJECTS.map((p) => {
            const isSelected = p.id === selectedProjectId;
            return (
              <button
                key={p.id}
                onClick={() => setSelectedProjectId(p.id)}
                className={`p-3.5 rounded-xl border text-left transition-all cursor-pointer ${
                  isSelected
                    ? 'bg-gradient-to-br from-emerald-950/40 to-slate-900 border-emerald-400 shadow-lg shadow-emerald-500/15'
                    : 'bg-slate-900/40 border-slate-800 hover:border-slate-700'
                }`}
              >
                <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-emerald-500/15 text-emerald-300 border border-emerald-500/30 inline-block mb-1.5">
                  {p.sdg.split(':')[0]}
                </span>
                <h2 className="text-xs font-bold text-white truncate mb-1">
                  {p.title.split(':')[0]}
                </h2>
                <p className="text-[11px] text-slate-400 line-clamp-2">
                  {p.targetUsers}
                </p>
              </button>
            );
          })}
        </div>
      </div>

      {/* Main Project Details */}
      <div className="glass-panel rounded-2xl p-6 space-y-6">
        
        {/* Project Header Banner */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-5 border-b border-slate-800">
          <div>
            <span className="text-xs font-bold text-emerald-400 block mb-1">
              {project.sdg}
            </span>
            <h2 className="text-xl sm:text-2xl font-extrabold text-white">
              {project.title}
            </h2>
            <div className="flex items-center gap-2 mt-2 text-xs text-slate-300">
              <Target className="w-3.5 h-3.5 text-violet-400" />
              <span><strong>Destinatari:</strong> {project.targetUsers}</span>
            </div>
          </div>

          <div className="flex items-center gap-1.5 bg-slate-900/80 p-1.5 rounded-xl border border-slate-800 self-start sm:self-auto">
            <button
              onClick={() => setActiveTab('overview')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'overview'
                  ? 'bg-emerald-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Panoramica
            </button>
            <button
              onClick={() => setActiveTab('architecture')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'architecture'
                  ? 'bg-emerald-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Architettura
            </button>
            <button
              onClick={() => setActiveTab('code')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'code'
                  ? 'bg-emerald-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Codice Starter
            </button>
            <button
              onClick={() => setActiveTab('datasets')}
              className={`px-3 py-1.5 rounded-lg text-xs font-bold transition-all cursor-pointer ${
                activeTab === 'datasets'
                  ? 'bg-emerald-600 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Dataset
            </button>
          </div>
        </div>

        {/* Tab 1: Overview */}
        {activeTab === 'overview' && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-2">
              <span className="text-xs font-bold text-rose-400 uppercase tracking-wider block">
                Problema nel Mondo Reale:
              </span>
              <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                {renderBionicText(project.problem, bionicReading)}
              </p>
            </div>

            <div className="p-5 rounded-xl bg-emerald-950/20 border border-emerald-500/30 space-y-2">
              <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider block">
                Soluzione Guidata dall'AI:
              </span>
              <p className="text-xs sm:text-sm text-slate-200 leading-relaxed">
                {renderBionicText(project.solution, bionicReading)}
              </p>
            </div>

            <div className="md:col-span-2 p-4 rounded-xl bg-violet-950/20 border border-violet-500/30 flex items-start gap-3">
              <Sparkles className="w-4 h-4 text-violet-400 shrink-0 mt-0.5" />
              <div>
                <span className="text-xs font-bold text-violet-300 block mb-0.5">Pitch Hook per i Giudici:</span>
                <p className="text-xs text-slate-300 italic">
                  "{project.pitchHook}"
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Tab 2: Architecture */}
        {activeTab === 'architecture' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                Pipeline Dati & Modello ({project.aiTechnique}):
              </span>
            </div>
            <pre className="p-5 rounded-xl bg-slate-950 border border-slate-800 text-emerald-400 font-mono text-xs overflow-x-auto whitespace-pre leading-relaxed">
              {project.architecture}
            </pre>
          </div>
        )}

        {/* Tab 3: Starter Code */}
        {activeTab === 'code' && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-mono text-slate-400">starter_pipeline.py</span>
              <button
                onClick={handleCopyCode}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium transition-colors cursor-pointer"
              >
                {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedCode ? 'Copiato!' : 'Copia Codice'}</span>
              </button>
            </div>
            <pre className="p-5 rounded-xl bg-slate-950 border border-slate-800 text-cyan-300 font-mono text-xs overflow-x-auto whitespace-pre-wrap leading-relaxed">
              {project.starterCodePython}
            </pre>
          </div>
        )}

        {/* Tab 4: Recommended Datasets */}
        {activeTab === 'datasets' && (
          <div className="grid gap-4 sm:grid-cols-2">
            {project.recommendedDatasets.map((ds, idx) => (
              <div key={idx} className="p-4 rounded-xl bg-slate-900/60 border border-slate-800 flex flex-col justify-between space-y-3">
                <div>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-bold text-white">{ds.name}</span>
                    <Database className="w-3.5 h-3.5 text-slate-500" />
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">
                    {ds.desc}
                  </p>
                </div>
                <a
                  href={ds.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 text-xs font-semibold text-emerald-400 hover:text-emerald-300 transition-colors"
                >
                  <span>Esplora Dataset</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              </div>
            ))}
          </div>
        )}

      </div>
    </div>
  );
}
